# .github/dependabot.yml
# Configuración automática de Dependabot para security y maintenance
version: 2

updates:
  # Frontend dependencies (cuando lo tengamos)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Bogota"
    reviewers:
      - "Franklin-Andres-Rodriguez"
    assignees:
      - "Franklin-Andres-Rodriguez"
    commit-message:
      prefix: "deps(frontend)"
      include: "scope"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "frontend"
      - "automated"

  # Root project dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Bogota"
    reviewers:
      - "Franklin-Andres-Rodriguez"
    assignees:
      - "Franklin-Andres-Rodriguez"
    commit-message:
      prefix: "deps(root)"
      include: "scope"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "root"
      - "automated"

  # Microservices dependencies (para futuras fases)
  - package-ecosystem: "npm"
    directory: "/services/auth-service"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/Bogota"
    reviewers:
      - "Franklin-Andres-Rodriguez"
    commit-message:
      prefix: "deps(auth)"
      include: "scope"
    labels:
      - "dependencies"
      - "auth-service"
      - "automated"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/Bogota"
    reviewers:
      - "Franklin-Andres-Rodriguez"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "ci-cd"
      - "automated"

  # Docker dependencies (para futuras fases)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "America/Bogota"
    reviewers:
      - "Franklin-Andres-Rodriguez"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"