name: 'SICP Assessment'
description: 'Runs SICP assessment checks on the repository'
inputs:
  token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'