name: 🐛 Bug Report
description: File a bug report to help us improve the platform
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: ["Franklin-Andres-Rodriguez"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Preparación Académica - Bug Report
        
        Thank you for helping improve our educational platform! **Quality bug reports accelerate fixes by 3-5x** - this template guides you through providing the essential information we need.
        
        > 💡 **Educational Tip**: Professional bug reports following systematic methodology (like SICP) enable faster resolution and prevent regression. This mirrors debugging best practices we teach!

  - type: dropdown
    id: component
    attributes:
      label: 🏗️ Affected Component  
      description: Which part of the system is experiencing issues?
      options:
        - "📚 Documentation (README, guides, tutorials)"
        - "🔧 Development Scripts (setup, validation, testing)"
        - "⚙️ GitHub Automation (workflows, templates, actions)"
        - "🔒 Security Features (Dependabot, CodeQL, scanning)"
        - "🎓 Educational Content (methodology, examples)"
        - "🏗️ Project Structure (directories, configuration)"
        - "📦 Dependencies (package management, versions)"
        - "🌐 Repository Settings (branch protection, permissions)"
        - "Other (please specify in description)"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Bug Severity
      description: How severely does this impact the educational experience?
      options:
        - "🟥 Critical - Blocks learning/development completely"
        - "🟧 High - Major feature broken, significant impact" 
        - "🟨 Medium - Feature partially working, workaround available"
        - "🟩 Low - Minor issue, minimal impact on learning"
        - "🟦 Enhancement - Improvement suggestion"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Bug Description
      description: |
        **Clear, concise description of what went wrong.**
        
        **Educational Note**: This follows **Systematic Observation** from SICP methodology - document symptoms precisely before analyzing causes.
      placeholder: |
        Example: "The validate-prerequisites.sh script fails on macOS when checking Docker daemon status, even when Docker Desktop is running correctly."
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: |
        **Precise steps that consistently reproduce the issue.**
        
        **Educational Note**: Reproducible steps enable **Systematic Testing** - a core SICP principle for isolation and verification.
      placeholder: |
        1. Open terminal on macOS Monterey 12.6
        2. Run `./scripts/validate-prerequisites.sh`
        3. Script reaches Docker validation step
        4. See error: "Docker daemon is not running" despite Docker Desktop being active
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should happen instead?
      placeholder: "Script should detect running Docker daemon and show '✅ Docker X.X.X is running'"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: ❌ Actual Behavior  
      description: What actually happened?
      placeholder: "Script shows '❌ Docker daemon is not running' and exits with error code 1"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment Information
      description: |
        **Complete environment details for accurate diagnosis.**
        
        **Educational Note**: Environment context is crucial for **Hypothesis Formation** - different environments often reveal different causes.
      placeholder: |
        - OS: macOS Monterey 12.6
        - Node.js: v18.17.0 (via nvm)
        - Docker: Docker Desktop 4.21.1
        - Shell: zsh 5.8.1
        - Terminal: iTerm2 3.4.19
        - Git: 2.40.1
      value: |
        - OS: 
        - Node.js: 
        - Docker: 
        - Shell: 
        - Terminal: 
        - Git: 
    validations:
      required: true

  - type: textarea
    id: logs_screenshots
    attributes:
      label: 📸 Error Logs / Screenshots
      description: |
        **Paste error messages, logs, or attach screenshots.**
        
        **Educational Note**: Raw error data supports **Root Cause Analysis** - the evidence needed to identify true causes vs symptoms.
      placeholder: |
        ```bash
        $ ./scripts/validate-prerequisites.sh
        🔍 Validating Preparación Académica development prerequisites...
        ✅ Node.js 18.17.0 is compatible
        ✅ npm 9.6.7 is available
        ❌ Docker daemon is not running
           Please start Docker Desktop or Docker daemon
        ```

  - type: textarea
    id: attempted_solutions
    attributes:
      label: 🔧 Attempted Solutions
      description: What have you tried to fix this issue?
      placeholder: |
        - Restarted Docker Desktop
        - Checked Docker daemon with `docker info` (works fine)
        - Verified Docker command in script logic
    
  - type: checkboxes
    id: impact_assessment
    attributes:
      label: 📊 Impact Assessment
      description: How does this bug affect the educational experience?
      options:
        - label: "🚫 Prevents new students from setting up development environment"
        - label: "⏰ Causes significant delays in getting started with learning"
        - label: "😤 Creates frustration that could discourage learning"
        - label: "🐛 Affects multiple users (not just me)"
        - label: "📚 Impacts understanding of development best practices"

  - type: checkboxes
    id: pre_submission_checklist
    attributes:
      label: ✅ Pre-submission Checklist
      description: Please confirm before submitting
      options:
        - label: "🔍 I searched existing issues for duplicates"
          required: true
        - label: "📝 I provided complete reproduction steps"
          required: true
        - label: "🖥️ I included comprehensive environment information"
          required: true
        - label: "🔄 I can reproduce this issue consistently"
          required: true
        - label: "📊 I assessed the educational impact accurately"
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🎓 **Educational Value of Quality Bug Reports**
        
        By completing this detailed bug report, you're practicing:
        - **📋 Systematic Observation** - documenting symptoms clearly
        - **🧠 Hypothesis Formation** - considering environment factors  
        - **🔬 Evidence Gathering** - providing logs and reproduction steps
        - **📊 Impact Analysis** - assessing severity and scope
        
        **These skills directly transfer to professional debugging methodology!**
        
        ---
        
        Thank you for contributing to **Preparación Académica**! Your detailed report helps maintain the high-quality educational experience we strive to provide. 🚀